#ifndef NEXUSBUILDER_GLOBAL_H
#define NEXUSBUILDER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NEXUSBUILDER_LIBRARY)
#  define NEXUSBUILDER_EXPORT Q_DECL_EXPORT
#else
#  define NEXUSBUILDER_EXPORT Q_DECL_IMPORT
#endif

#endif // NEXUSBUILDER_GLOBAL_H
